spring:
  application:
    name: jen-ventory-api
  datasource:
    url: jdbc:postgresql://localhost:5432/database_name
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

security:
  jwt:
    secret: your-secret-key
    access-token:
      expiration: 900000 # 15 minutes
    refresh-token:
      expiration: 604800000 # 7 days